# Generated by Django 4.1 on 2022-10-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0026_criminal_time_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='Time_left',
        ),
    ]
