# Generated by Django 4.1 on 2022-10-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0032_criminal_timeleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='TimeLeft',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
