# Generated by Django 4.1.2 on 2022-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0034_criminal_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='Item',
        ),
        migrations.AddField(
            model_name='visitor',
            name='Item',
            field=models.CharField(blank=True, choices=[('Money', 'Money'), ('Food', 'Food'), ('Cloth', 'Cloth')], max_length=20, null=True),
        ),
    ]
