# Generated by Django 4.1.2 on 2022-10-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0035_remove_criminal_item_visitor_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='VisitorsAllowed',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
