# Generated by Django 4.1.2 on 2022-11-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0012_court_release_transfer'),
        ('record', '0038_criminal_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='CourtName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison.court'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='EntranceTime',
            field=models.TimeField(null=True),
        ),
    ]
