# Generated by Django 4.1.2 on 2022-11-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0012_court_release_transfer'),
        ('record', '0039_criminal_courtname_criminal_entrancetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='Release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison.release'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='Transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison.transfer'),
        ),
    ]
